### ISSUE TITLE
Невозможность подключиться к ABB IRB 140 по IP

### ISSUE THREAD

**Issue by RazThePsycho** [solid-sinusoid/abb_irb140_packages#2]
Приветствую!
При вводе команды для запуска на реальном роботе выходит следующая ошибка:
`[ERROR] : Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ERROR] : Failed to receive message length
[ERROR] : Failed to receive incoming message`
IP адрес робота для подключения сделали как 192.168.0.10, если отрубаем, то 192.168.125.1, но при этих двух случаях адреса пингуются, но к роботу подключится не удается. Если же подключатся через софт RobotStudio, то без проблем. Как решить этот момент чтобы чисто по ROS удалось бы подключиться? Спасибо

**Comment by solid-sinusoid** [comment]
@RazThePsycho Я точно помню, что использовал IP на планшете контроллера. Может у вас другая версия контроллера на роботе? Просто на относительно новых контроллерах используется немного другой подход с большим реалтаймом через специальную библиотечку от ABB
